config/routes.rb
Subbit::Application.routes.draw do
  get "posts/show"
  get "blogs/index"
  get "blogs/show"

  match '/', to: 'blogs#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
  match '/', to: 'blogs#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
  root "blogs#index"
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_blog

  private
    def get_blog
      blogs = Blog.where(subdomain: request.subdomain)
      if blogs.count > 0
        @blog = blogs.first
      elsif request.subdomain != 'www'
        redirect_to root_url(subdomain: 'www')
      end
    end  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    logger.debug("hitting the index")
    @blogs = Blog.all
  end
  def show
    @posts = @blog.posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = @blog.posts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/index.html.erb
<h1>Blogs on this Server</h1>
<ul>
  <% @blogs.each do |blog| %>
    <li><%= link_to blog.name, root_url(subdomain: blog.subdomain) %></li>
  <% end %>
</ul>

app/views/blogs/show.html.erb
<h1><%= @blog.name %></h1>
<hr />
<% @posts.each do |post| %>

<h3><%= post.title %></h3>
<p><%= truncate post.body, length: 160 %></p>
<%= link_to "Read More", posts_show_path(post.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubdomainsExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
  <%= @post.body %>
</p>